version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install

  pre_build:
    commands:
      - echo Compiling TypeScript files...
      - npm run build

  build:
    commands:
      - echo Build phase completed. Ready to deploy.

  post_build:
    commands:
      - echo Build and packaging completed.

artifacts:
  files:
    - "dist/**/*" # Archivos compilados en dist
    - "package.json"
    - "package-lock.json"
    - "!node_modules/**" # Opcional, si no quieres incluir node_modules

cache:
  paths:
    - node_modules/**/*
